export const changelog = [
  {
    version: '2.4.0',
    date: '2026-02-16',
    changes: [
      'Production readiness improvements',
      'Removed unsafe-eval from Content Security Policy',
      'Removed sensitive info from health endpoint',
      'Fixed Gmail provider option in admin email settings',
      'Fixed database backup endpoint URL',
      'Added MFA and backup encryption key support in Docker config',
      'Removed console.log statements from frontend',
      'Updated documentation and deployment guide',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-02-16',
    changes: [
      'Added one-click update from the Help page (streams progress, auto-reconnects after restart)',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-02-16',
    changes: [
      'Release 2.2.0',
    ],
  },
  {
    version: '2.1.10',
    date: '2026-02-13',
    changes: [
      'Fixed Nginx configuration to correctly pass proxy headers',
    ],
  },
  {
    version: '2.1.9',
    date: '2026-02-13',
    changes: [
      'Improved Nginx Proxy Manager compatibility (HTTPS detection)',
    ],
  },
  {
    version: '2.1.8',
    date: '2026-02-13',
    changes: [
      'Synced package versions to ensure correct update detection',
    ],
  },
  {
    version: '2.1.7',
    date: '2026-02-13',
    changes: [
      'Fixed update check logic to reliably detect current version',
    ],
  },
  {
    version: '2.1.6',
    date: '2026-02-13',
    changes: [
      'Hardcoded lowercase repository owner for Docker images',
    ],
  },
  {
    version: '2.1.5',
    date: '2026-02-13',
    changes: [
      'Fixed Docker image naming in release pipeline',
    ],
  },
  {
    version: '2.1.4',
    date: '2026-02-13',
    changes: [
      'Fixed release pipeline trigger to run on tag pushes',
    ],
  },
  {
    version: '2.1.3',
    date: '2026-02-13',
    changes: [
      'Fixed incorrect test database port configuration',
    ],
  },
  {
    version: '2.1.2',
    date: '2026-02-13',
    changes: [
      'Fixed critical database connection issues in CI/CD pipeline',
      'Improved backend test stability',
    ],
  },
  {
    version: '2.1.1',
    date: '2026-02-13',
    changes: [
      'Moved "Check Updates" button to Help page for better accessibility',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-02-09',
    changes: [
      '🎉 NOW FULLY OPEN SOURCE - All features completely free!',
      '❌ Removed subscription system - No payment barriers',
      '✅ All premium features now available to everyone',
      '📊 Analytics - Free for all users',
      '🏢 Organizations - Team collaboration for everyone',
      '🧾 Receipts - Unlimited uploads',
      '✨ Budget Templates - All templates available',
      '💱 Multi-Currency - Full support for 20 currencies',
      '🔔 Notifications - Real-time alerts for all',
      '🚀 Self-host your own instance',
      '🌟 No usage limits or restrictions',
      '📝 Simplified navigation - removed feature badges',
      '🔓 100% free and open source budget tracker',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-02-09',
    changes: [
      '🎉 MAJOR RELEASE: Complete SaaS Platform Transformation',
      '✅ Complete UI Integration - All SaaS features now accessible in the interface',
      '📱 New Navigation - Reorganized into 5 sections with feature badges (New, Pro, Business, SaaS)',
      '💳 Subscriptions Page - Plan comparison, upgrade flow, billing management',
      '🏢 Organizations Page - Team collaboration, member invitations, role management',
      '🧾 Receipts Page - Upload images, gallery view, transaction linking',
      '✨ Budget Templates Page - Apply pre-built budgeting strategies (50/30/20, Zero-based, etc.)',
      '💱 Currency Page - Multi-currency support with 20+ currencies',
      '🔔 Notifications Page - Real-time alerts with preferences',
      '📊 Analytics Dashboard - 6 chart types with CSV export',
      '💰 Stripe subscription management (Free, Pro $9.99, Business $29.99)',
      '🏢 Multi-tenancy with organizations and role-based access',
      '📈 Usage tracking and automatic plan limit enforcement',
      '📁 Receipt management with file upload (S3 or local storage)',
      '📋 Budget templates system with 4 pre-built templates',
      '🌍 Multi-currency support with live exchange rates',
      '🔔 Real-time notifications with Socket.io WebSocket',
      '📱 Progressive Web App (PWA) with offline support',
      '⚡ Service worker for caching and background sync',
      '🧪 Comprehensive testing suite (29 integration tests)',
      '🚀 CI/CD pipeline with GitHub Actions',
      '🐛 Error tracking with Sentry',
      '⚡ Redis caching for performance',
      '🛡️ Rate limiting on all endpoints',
      '🔒 Response compression and security headers',
      '📚 Interactive API documentation with Swagger',
      '☁️ Complete production deployment guide',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-02-07',
    changes: [
      'Pay Periods page — assign bills to income buckets (paychecks, bonuses, freelance)',
      'See how much of each paycheck is spoken for with remaining balance tracking',
      'Recurring pay period support with auto-generation (weekly, biweekly, semi-monthly, monthly)',
      'Quick-assign and reassign bills between pay periods',
      'Unassigned bills section for easy bill management',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-02-07',
    changes: [
      'Help page with quick-start instructions and full changelog',
      'Version number displayed in sidebar and mobile header',
      'Sidebar navigation consolidated into grouped sections (Finances, Manage, Tools)',
      'Calendar and Sharing quick-access icons in top bar',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-01-01',
    changes: [
      'Initial release',
      'Dashboard with spending overview and charts',
      'Transaction management (add, edit, delete, filter)',
      'Budget tracking with category-based limits',
      'Recurring transactions with automatic scheduling',
      'Category management with custom colors and icons',
      'Debt tracking',
      'Bill management',
      'CSV/bank statement import',
      'Budget sharing with view/edit permissions',
      'Calendar view for transactions and bills',
      'Two-factor authentication (TOTP)',
      'Data backup and restore',
      'Dark mode support',
      'Admin dashboard with user management and activity logs',
    ],
  },
];
