export const changelog = [
  {
    version: '1.0.0',
    date: '2026-02-08',
    changes: [
      '🎉 MAJOR RELEASE: Complete SaaS Platform Transformation',
      'Stripe subscription management (Free, Pro $9.99, Business $29.99)',
      'Multi-tenancy with organizations and role-based access',
      'Usage tracking and automatic plan limit enforcement',
      'Advanced analytics dashboard with 6 chart types and CSV export',
      'Receipt management with file upload (S3 or local storage)',
      'Budget templates system with 4 pre-built templates',
      'Multi-currency support for 20 currencies with live exchange rates',
      'Real-time notifications with Socket.io WebSocket',
      'Progressive Web App (PWA) with offline support',
      'Service worker for caching and background sync',
      'Comprehensive testing suite (29 integration tests)',
      'CI/CD pipeline with GitHub Actions',
      'Error tracking with Sentry',
      'Redis caching for performance',
      'Rate limiting on all endpoints',
      'Response compression and security headers',
      'Load testing framework with k6',
      'Interactive API documentation with Swagger',
      'Complete production deployment guide',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-02-07',
    changes: [
      'Pay Periods page — assign bills to income buckets (paychecks, bonuses, freelance)',
      'See how much of each paycheck is spoken for with remaining balance tracking',
      'Recurring pay period support with auto-generation (weekly, biweekly, semi-monthly, monthly)',
      'Quick-assign and reassign bills between pay periods',
      'Unassigned bills section for easy bill management',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-02-07',
    changes: [
      'Help page with quick-start instructions and full changelog',
      'Version number displayed in sidebar and mobile header',
      'Sidebar navigation consolidated into grouped sections (Finances, Manage, Tools)',
      'Calendar and Sharing quick-access icons in top bar',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-01-01',
    changes: [
      'Initial release',
      'Dashboard with spending overview and charts',
      'Transaction management (add, edit, delete, filter)',
      'Budget tracking with category-based limits',
      'Recurring transactions with automatic scheduling',
      'Category management with custom colors and icons',
      'Debt tracking',
      'Bill management',
      'CSV/bank statement import',
      'Budget sharing with view/edit permissions',
      'Calendar view for transactions and bills',
      'Two-factor authentication (TOTP)',
      'Data backup and restore',
      'Dark mode support',
      'Admin dashboard with user management and activity logs',
    ],
  },
];
