export const changelog = [
  {
    version: '2.12.1',
    date: '2026-07-12',
    changes: [
      'Fixed “too many requests” errors during normal use of the desktop app — all rate limits (including the transaction and login limits) are now disabled in the desktop app, since it’s just you running your own copy.',
    ],
  },
  {
    version: '2.12.0',
    date: '2026-07-12',
    changes: [
      'AI categorization now learns: when you apply the AI’s category suggestions, it saves each merchant as an auto-categorization rule, so the same vendor is categorized automatically on future imports without spending an AI call. On by default (uncheck “Save as auto-categorization rules” to skip), and the rules are editable under Import → Match Rules.',
    ],
  },
  {
    version: '2.11.0',
    date: '2026-07-12',
    changes: [
      'Desktop app: on first launch, choose how it runs — Standalone (all on this computer), Server (host the data for other devices on your network), or Client (connect to a server on another computer). Change it anytime from File → Setup.',
      'Server ↔ Client traffic is now encrypted (HTTPS): a Server generates its own certificate, and each Client confirms it on first connect and warns if it ever changes — protecting your data on the network.',
      'AI: pick from the models your API key can actually use — “Fetch available” in Admin → AI Configuration loads the live list from Claude or OpenAI',
      'AI errors are now clear and actionable (e.g. rate limits explain the cause and suggest a faster model) instead of a generic failure',
      'New admin Error Log — application and AI errors are recorded to the database with full detail, searchable and exportable, so failures can actually be diagnosed',
      'Desktop app: downloadable Mac (.dmg) and Windows (.exe) installers are now published to GitHub Releases',
    ],
  },
  {
    version: '2.10.0',
    date: '2026-07-11',
    changes: [
      'Installable app — add Budget Tracker to your home screen or desktop with its own icon and window (Install app in the account menu, or your browser’s install button)',
      'Security hardening: tokens verified more strictly, refresh tokens stored hashed, logout now fully signs you out everywhere, and login lockout can no longer be triggered against your account from another device',
      'Household controls: only owners/admins can invite or remove members',
      'Scheduled backups now actually run on their schedule and are cleaned up per your retention setting',
      'Accessibility: screen-reader labels on icon buttons throughout the app',
      'Currency conversions now show a clear error if live rates are unavailable instead of silently using the wrong rate',
      'Reliability: hardened database backup scripts (verified with a full backup-and-restore drill) and a trustworthy automated test suite',
    ],
  },
  {
    version: '2.9.0',
    date: '2026-07-11',
    changes: [
      'Security: closed a backup-restore flaw that could let one account overwrite another’s data; backups no longer include password hashes or MFA secrets; first-admin bootstrap is now race-safe',
      'Fixed features that previously errored: multi-currency summary, applying a budget template, saving backup settings, and adding a family member with an allowance',
      'Backup Export, Restore, and Download now work end-to-end (with the correct file format and authenticated downloads)',
      'Reports: budget performance no longer over-counts spending across multi-month ranges, and category labels display correctly',
      'Money & dates: recurring items on the 29th–31st no longer skip months; transactions/imports land on the correct day regardless of timezone; debt balances are computed exactly',
      'Charts now theme correctly in dark mode (no more white tooltip boxes)',
      'Failed data loads now show a clear error with retry instead of a screen of zeros',
      'Much faster first load — the app is split into per-page bundles (initial download ~4× smaller)',
      'Installable PWA with safe offline caching that never stores your financial data; caches clear on logout',
      'Notifications are now reliably recorded; automatic cleanup keeps the database tidy',
    ],
  },
  {
    version: '2.8.0',
    date: '2026-07-02',
    changes: [
      'AI assistant now remembers your conversation and saves chat history across refreshes (with a Clear button)',
      'Choose your AI model from a dropdown per provider (Claude or OpenAI), plus a Custom option',
      'Clearer error messages app-wide: validation reasons, "already in use" / "still in use" hints, and a reference id for support',
      'Fixed AI transaction categorization getting cut off for large batches',
      'Fixed a login lockout caused by the session check tripping the brute-force limiter',
      'Import now accepts files up to 10 MB (was ~1 MB)',
      'Import no longer truncates OFX/QFX descriptions (uses the full memo field)',
    ],
  },
  {
    version: '2.7.0',
    date: '2026-07-02',
    changes: [
      'AI assistant now uses hosted providers — Anthropic Claude (default) or OpenAI — instead of a local Ollama model',
      'Removed the Ollama service, GPU detection, and in-app model downloads',
      'Admins configure the provider, model, and API keys under Admin → AI Configuration; keys are encrypted at rest',
    ],
  },
  {
    version: '2.6.0',
    date: '2026-07-02',
    changes: [
      'Security & stability hardening pass across the whole app',
      'Shared budgets rebuilt on Households (organizations); legacy budget_shares removed',
      'Fixed the database bootstrap so fresh and existing installs converge automatically on startup',
      'Removed the in-app one-click update endpoint (host-RCE risk); deploys are now operator-driven',
      'Fixed SQL-injection and ownership (IDOR) gaps; added server-side input validation across routes',
      'Receipts are now served through an authenticated, ownership-checked route (no more public /uploads)',
      'All sessions are revoked on password change / admin reset; stronger password policy',
      'App-wide error toasts + double-submit protection; safer money/date formatting',
      'Built out previously non-functional controls (receipt download/delete, currency default, more reports, household member management)',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-02-16',
    changes: [
      'AI-powered transaction categorization — select uncategorized transactions and let Ollama suggest categories',
      'Bulk "AI Categorize" button in transaction selection bar',
      'One-click "AI Categorize" header button for all uncategorized transactions in current month',
      'Review modal to accept, reject, or override AI suggestions before applying',
      'Increased nginx proxy timeout for AI endpoints to prevent failures on large batches',
    ],
  },
  {
    version: '2.4.2',
    date: '2026-02-16',
    changes: [
      'Fixed one-click update git authentication inside Docker container',
    ],
  },
  {
    version: '2.4.1',
    date: '2026-02-16',
    changes: [
      'Fixed one-click update failing due to git safe.directory issue in Docker container',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-02-16',
    changes: [
      'Production readiness improvements',
      'Removed unsafe-eval from Content Security Policy',
      'Removed sensitive info from health endpoint',
      'Fixed Gmail provider option in admin email settings',
      'Fixed database backup endpoint URL',
      'Added MFA and backup encryption key support in Docker config',
      'Removed console.log statements from frontend',
      'Updated documentation and deployment guide',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-02-16',
    changes: [
      'Added one-click update from the Help page (streams progress, auto-reconnects after restart)',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-02-16',
    changes: [
      'Release 2.2.0',
    ],
  },
  {
    version: '2.1.10',
    date: '2026-02-13',
    changes: [
      'Fixed Nginx configuration to correctly pass proxy headers',
    ],
  },
  {
    version: '2.1.9',
    date: '2026-02-13',
    changes: [
      'Improved Nginx Proxy Manager compatibility (HTTPS detection)',
    ],
  },
  {
    version: '2.1.8',
    date: '2026-02-13',
    changes: [
      'Synced package versions to ensure correct update detection',
    ],
  },
  {
    version: '2.1.7',
    date: '2026-02-13',
    changes: [
      'Fixed update check logic to reliably detect current version',
    ],
  },
  {
    version: '2.1.6',
    date: '2026-02-13',
    changes: [
      'Hardcoded lowercase repository owner for Docker images',
    ],
  },
  {
    version: '2.1.5',
    date: '2026-02-13',
    changes: [
      'Fixed Docker image naming in release pipeline',
    ],
  },
  {
    version: '2.1.4',
    date: '2026-02-13',
    changes: [
      'Fixed release pipeline trigger to run on tag pushes',
    ],
  },
  {
    version: '2.1.3',
    date: '2026-02-13',
    changes: [
      'Fixed incorrect test database port configuration',
    ],
  },
  {
    version: '2.1.2',
    date: '2026-02-13',
    changes: [
      'Fixed critical database connection issues in CI/CD pipeline',
      'Improved backend test stability',
    ],
  },
  {
    version: '2.1.1',
    date: '2026-02-13',
    changes: [
      'Moved "Check Updates" button to Help page for better accessibility',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-02-09',
    changes: [
      '🎉 NOW FULLY OPEN SOURCE - All features completely free!',
      '❌ Removed subscription system - No payment barriers',
      '✅ All premium features now available to everyone',
      '📊 Analytics - Free for all users',
      '🏢 Organizations - Team collaboration for everyone',
      '🧾 Receipts - Unlimited uploads',
      '✨ Budget Templates - All templates available',
      '💱 Multi-Currency - Full support for 20 currencies',
      '🔔 Notifications - Real-time alerts for all',
      '🚀 Self-host your own instance',
      '🌟 No usage limits or restrictions',
      '📝 Simplified navigation - removed feature badges',
      '🔓 100% free and open source budget tracker',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-02-09',
    changes: [
      '🎉 MAJOR RELEASE: Complete SaaS Platform Transformation',
      '✅ Complete UI Integration - All SaaS features now accessible in the interface',
      '📱 New Navigation - Reorganized into 5 sections with feature badges (New, Pro, Business, SaaS)',
      '💳 Subscriptions Page - Plan comparison, upgrade flow, billing management',
      '🏢 Organizations Page - Team collaboration, member invitations, role management',
      '🧾 Receipts Page - Upload images, gallery view, transaction linking',
      '✨ Budget Templates Page - Apply pre-built budgeting strategies (50/30/20, Zero-based, etc.)',
      '💱 Currency Page - Multi-currency support with 20+ currencies',
      '🔔 Notifications Page - Real-time alerts with preferences',
      '📊 Analytics Dashboard - 6 chart types with CSV export',
      '💰 Stripe subscription management (Free, Pro $9.99, Business $29.99)',
      '🏢 Multi-tenancy with organizations and role-based access',
      '📈 Usage tracking and automatic plan limit enforcement',
      '📁 Receipt management with file upload (S3 or local storage)',
      '📋 Budget templates system with 4 pre-built templates',
      '🌍 Multi-currency support with live exchange rates',
      '🔔 Real-time notifications with Socket.io WebSocket',
      '📱 Progressive Web App (PWA) with offline support',
      '⚡ Service worker for caching and background sync',
      '🧪 Comprehensive testing suite (29 integration tests)',
      '🚀 CI/CD pipeline with GitHub Actions',
      '🐛 Error tracking with Sentry',
      '⚡ Redis caching for performance',
      '🛡️ Rate limiting on all endpoints',
      '🔒 Response compression and security headers',
      '📚 Interactive API documentation with Swagger',
      '☁️ Complete production deployment guide',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-02-07',
    changes: [
      'Pay Periods page — assign bills to income buckets (paychecks, bonuses, freelance)',
      'See how much of each paycheck is spoken for with remaining balance tracking',
      'Recurring pay period support with auto-generation (weekly, biweekly, semi-monthly, monthly)',
      'Quick-assign and reassign bills between pay periods',
      'Unassigned bills section for easy bill management',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-02-07',
    changes: [
      'Help page with quick-start instructions and full changelog',
      'Version number displayed in sidebar and mobile header',
      'Sidebar navigation consolidated into grouped sections (Finances, Manage, Tools)',
      'Calendar and Sharing quick-access icons in top bar',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-01-01',
    changes: [
      'Initial release',
      'Dashboard with spending overview and charts',
      'Transaction management (add, edit, delete, filter)',
      'Budget tracking with category-based limits',
      'Recurring transactions with automatic scheduling',
      'Category management with custom colors and icons',
      'Debt tracking',
      'Bill management',
      'CSV/bank statement import',
      'Budget sharing with view/edit permissions',
      'Calendar view for transactions and bills',
      'Two-factor authentication (TOTP)',
      'Data backup and restore',
      'Dark mode support',
      'Admin dashboard with user management and activity logs',
    ],
  },
];
